_BASE_: "Base-FCOS.yaml"
MODEL:
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  BiFPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 160
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
OUTPUT_DIR: "output/fcos/MS_R_101_BiFPN_2x"
