_BASE_: "Base-FCOS.yaml"
MODEL:
  BACKBONE:
    NAME: "build_fcos_resnet_panet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  PANET:
    IN_FEATURES: ["p3", "p4", "p5"]
  FCOS:
    IN_FEATURES: ["n3", "n4", "n5", "n6", "n7"]
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
OUTPUT_DIR: "output/fcos/R_50_PANET_1x"
