_BASE_: "Base-FCOS.yaml"
MODEL:
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BiFPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 160
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
OUTPUT_DIR: "output/fcos/R_50_BiFPN_1x"
