_BASE_: "Base-TotalText.yaml"
MODEL:
  WEIGHTS: "attn_pretrain.pth"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn" # "attn" "rnn"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  STEPS: (80000, 120000)
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/batext/totaltext/attn_R_50"
